"""initial migration

Revision ID: 9f4d7fd2e129
Revises: 
Create Date: 2023-03-07 15:58:21.553650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f4d7fd2e129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Shows')
    op.drop_table('venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_id',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('contact', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('facebook link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('image_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='venue_id_artist_id_fkey')
    )
    op.create_table('Shows',
    sa.Column('show_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Shows_show_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('venue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('artist', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fblink', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('Imglink', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('show_id', name='Shows_pkey')
    )
    # ### end Alembic commands ###
