"""correct column spellings

Revision ID: f03bd02ea7df
Revises: f088dbdb9059
Create Date: 2023-03-12 18:03:20.645214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03bd02ea7df'
down_revision = 'f088dbdb9059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=True))
        batch_op.drop_column('genre')
        batch_op.drop_column('website')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('genres')
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
